"""Add visited_urls table

Revision ID: 003211a6b893
Revises: ffa04d618d3d
Create Date: 2025-07-08 11:08:59.205751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '003211a6b893'
down_revision: Union[str, Sequence[str], None] = 'ffa04d618d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitedurl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('last_visited_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitedurl_domain'), 'visitedurl', ['domain'], unique=False)
    op.create_index(op.f('ix_visitedurl_last_visited_date'), 'visitedurl', ['last_visited_date'], unique=False)
    op.create_index(op.f('ix_visitedurl_url'), 'visitedurl', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitedurl_url'), table_name='visitedurl')
    op.drop_index(op.f('ix_visitedurl_last_visited_date'), table_name='visitedurl')
    op.drop_index(op.f('ix_visitedurl_domain'), table_name='visitedurl')
    op.drop_table('visitedurl')
    # ### end Alembic commands ###
