"""Add visited_urls table

Revision ID: 28e52baa9d13
Revises: ffa04d618d3d
Create Date: 2025-07-08 11:29:18.344622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '28e52baa9d13'
down_revision: Union[str, Sequence[str], None] = 'ffa04d618d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitedurl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('last_visited_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitedurl_domain'), 'visitedurl', ['domain'], unique=False)
    op.create_index(op.f('ix_visitedurl_last_visited_date'), 'visitedurl', ['last_visited_date'], unique=False)
    op.create_index(op.f('ix_visitedurl_url'), 'visitedurl', ['url'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agentrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_index(op.f('ix_visitedurl_url'), table_name='visitedurl')
    op.drop_index(op.f('ix_visitedurl_last_visited_date'), table_name='visitedurl')
    op.drop_index(op.f('ix_visitedurl_domain'), table_name='visitedurl')
    op.drop_table('visitedurl')
    op.drop_table('agentrun')
    # ### end Alembic commands ###
