"""Add evaluated_snippets table

Revision ID: 893227fad414
Revises: 003211a6b893
Create Date: 2025-07-08 17:39:13.140890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893227fad414'
down_revision: Union[str, Sequence[str], None] = '003211a6b893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluated_snippets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content_summary', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluated_snippets_id'), 'evaluated_snippets', ['id'], unique=False)
    op.create_index(op.f('ix_evaluated_snippets_url'), 'evaluated_snippets', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluated_snippets_url'), table_name='evaluated_snippets')
    op.drop_index(op.f('ix_evaluated_snippets_id'), table_name='evaluated_snippets')
    op.drop_table('evaluated_snippets')
    # ### end Alembic commands ###
